### ISSUE TITLE
file path

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-data-summarization#1]
The best practice for reading and writing file paths in Python is os.path.join. I suggest using os.path.join instead of a string as a path, such as 'images\svg4.svg'. Or it might trigger an error on Mac or Linux environment
<img width="863" alt="Screenshot 2023-08-22 at 5 34 53 PM" src="https://github.com/cbdb-project/cbdb-data-summarization/assets/8538710/12e3b86c-01c0-4091-b60e-3edbea43208f">

**Comment by oscarchen666** [comment]
Thank you for pointing out this issue. I have fixed this issue by using`./images/svg4. svg `.

**Comment by sudoghut** [comment]
非常感谢！

这样来写带来一个小问题就是不能在 windows 下面跑。Python 下跨平台使用文件或者目录的最佳实践是 os.path.join. 示例如下：

```
import os
path = os.path.join(os.getcwd(), 'images', 'svg4.svg')
```

麻烦 @oscarchen666 啦

**Comment by oscarchen666** [comment]
那还挺奇怪的，因为我本地就是在windows成功运行的。包括前面的`latest_file = "./cbdb_sqlite/latest.7z"`也是直接用字符串的形式。但是您说的确实是更规范的用法，我会进行修改的

**Comment by sudoghut** [comment]
感谢 @oscarchen666 分享的实践结果。之前我也发现 win 和 mac 的目录书写兼容性不太平衡。可能因为身边大家的 python 版本比较复杂，所以一直没有发现这件事。
