### ISSUE TITLE
繁体中文

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-data-summarization#2]
当前标题都是简体中文。因为数据库的所有数据都是繁中，我把 <tspan> 的内容也替换成了繁中：

得到 @oscarchen666 的确认之后我就关掉这个 issue

![image](https://github.com/cbdb-project/cbdb-data-summarization/assets/8538710/34e0f483-e4fc-4035-bf14-eca3ef447ee4)

**Comment by oscarchen666** [comment]
@sudoghut 当然可以！网页的设计还没有最终定稿，所以我们并没有注意这些细节，如果您顺手帮忙修改了当然再好不过。
