### ISSUE TITLE
关于token的问题

### ISSUE THREAD

**Issue by oscarchen666** [cbdb-project/cbdb-data-summarization#3]
我已经在cbdb_sqlite仓库部署了监测push并请求该仓库的更新的action。
![image](https://github.com/cbdb-project/cbdb-data-summarization/assets/74868097/1e8187a4-add1-40f7-8f16-2f51f0f085bf)
![image](https://github.com/cbdb-project/cbdb-data-summarization/assets/74868097/e2ce209c-166b-4b43-8c72-28251d3642c9)

但是，我使用的是您在cbdb_sqlite仓库的secrets中保存的token`${{ secrets.GH_TOKEN }}"`。因为我似乎没有权限打开cbdb_sqlite仓库的setting添加自己的token（上图中没有setting选项），不知道用您的token您是否会介意或者有什么风险，又或者我应该怎么获得权限去添加自己的token？
@sudoghut 😀

**Comment by sudoghut** [comment]
感谢！这里的 token 其实是在自己账号里面设置的（而不是在项目或者 organization 里面设置），在账号里面你可以选择让你的 token 继承你的哪些权限。

另一方面，直接用 `${{ secrets.GH_TOKEN }}" `也完全没问题。这样更方便，也更容易管理。

我提交了一个 sqlite 的测试 pr，对于 GitHub Actions 的触发非常完美。辛苦 @oscarchen666 了！

https://github.com/cbdb-project/cbdb-data-summarization/commit/14642c5bcdb5783ea716901735c777b94734dc66
