### ISSUE TITLE
update contributors

### ISSUE THREAD

**Issue by sudoghut** [cbdb-project/cbdb-data-summarization#4]
https://github.com/cbdb-project/cbdb-data-summarization/blob/main/README.md
@zwyixian @oscarchen666 张玮提到希望把 contributors 加上去。我在 readme 里面做了修改。拜托两位检查一下看看是否合适。
oscarchen666 的姓名我和不知道，也拜托 oscarchen666 把姓名（如果希望在 readme 里面留真实姓名）直接 update 到 readme 中。
得到确认之后，我就关掉这个 issue
麻烦两位啦！

**Comment by oscarchen666** [comment]
好的，已经和张玮确认并将我们俩的修改完了
